---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: Hello Terraform
      debug:
          msg: Hello Terraform!

    - name: Load config vars
      include_vars: tf_config.yml
      tags: always

    - name: Plan it
      include_role:
        name: "terraform-things"
        vars_from: plan.yml
      tags: plan

    - name: Apply it
      include_role:
        name: "terraform-things"
        vars_from: apply.yml
      tags: apply

    - name: Destroy it
      include_role:
        name: "terraform-things"
        vars_from: destroy.yml
      tags: destroy
