---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars_files:
    - vars/tf_config.yml
  tasks:
    - name: Plan it
      include_role:
        name: "terraform_things"
        vars_from: plan.yml
      tags: plan

    - name: Apply it
      include_role:
        name: "terraform_things"
        vars_from: apply.yml
      tags: apply

    - name: Destroy it
      include_role:
        name: "terraform_things"
        vars_from: destroy.yml
      tags: destroy
