- name: Terraform stuff!
  terraform2:
    project_path: "{{ project_path }}"
    state: "{{ state }}"
    force_init: "yes"
    plan_file: "{{ plan_file }}"
    lock: "{{ lock }}"
    targets: "{{ targets }}"
    variables: "{{ terraform_vars }}"
    variables_file: "{{ terraform_vars_file }}"
    workspace: "{{ workspace }}"
    backend_config:
      "{{ backend_config }}"
  register: result
  tags: always

- name: Display execution stdout
  debug:
    var: result.stdout_lines
  tags: always

- name: Display terraform outputs
  debug:
    var: result.outputs
  tags: apply